create table if not exists public.users (
  id uuid primary key default gen_random_uuid(),
  fullname text not null,
  email text not null unique,
  role text not null default 'user' check (role in ('user', 'admin'))
);

create or replace function public.sync_user_id_from_auth()
returns trigger
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if new.id is null then
    new.id := auth.uid();
  end if;

  if new.id is not null and new.id <> auth.uid() then
    new.id := auth.uid();
  end if;

  return new;
end;
$$;

do $$
begin
  if not exists (
    select 1
    from pg_trigger
    where tgname = 'users_sync_id_from_auth'
  ) then
    create trigger users_sync_id_from_auth
    before insert or update on public.users
    for each row
    execute function public.sync_user_id_from_auth();
  end if;
end $$;

-- Backfill existing data: match public.users rows to auth.users by email so bookings.user_id can resolve correctly.
update public.users u
set id = a.id
from auth.users a
where a.email = u.email
  and u.id is distinct from a.id;

alter table public.users enable row level security;

-- Helper: check admin role without triggering RLS recursion (SECURITY DEFINER bypasses RLS).
create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.users where id = auth.uid() and role = 'admin'
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

-- Remove old overly-open policies (safe to re-run).
drop policy if exists "Anyone can view users" on public.users;
drop policy if exists "Authenticated users can insert users" on public.users;
drop policy if exists "Authenticated users can insert own user row" on public.users;
drop policy if exists "Users can view own profile" on public.users;
drop policy if exists "Admins can view all users" on public.users;
drop policy if exists "Users can update own profile" on public.users;
drop policy if exists "Admins can update users" on public.users;

-- Users can only see their own row. Admins can see all rows.
create policy "Users can view own profile"
  on public.users for select
  using (auth.uid() = id);

create policy "Admins can view all users"
  on public.users for select
  using (public.is_admin());

-- New signups may only create their OWN row with role 'user' (blocks role='admin' escalation via direct API calls).
create policy "Authenticated users can insert own user row"
  on public.users for insert
  with check (auth.uid() is not null and auth.uid() = id and role = 'user');

-- Users may update their own name/email but may NOT change their role.
create policy "Users can update own profile"
  on public.users for update
  using (auth.uid() = id)
  with check (auth.uid() = id and role = 'user');

create policy "Admins can update users"
  on public.users for update
  using (public.is_admin())
  with check (public.is_admin());

create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id),
  booking_date date not null,
  pitch smallint not null check (pitch between 1 and 4),
  start_time time not null,
  status text not null default 'booked' check (status in ('booked', 'cancelled')),
  created_at timestamptz not null default now()
);

alter table public.bookings
  add column if not exists user_id uuid references auth.users(id);

create unique index if not exists bookings_active_slot_idx
  on public.bookings (booking_date, pitch, start_time)
  where status = 'booked';

alter table public.bookings enable row level security;

drop policy if exists "Anyone can view active bookings" on public.bookings;
drop policy if exists "Anyone can create bookings" on public.bookings;
drop policy if exists "Authenticated users can create bookings" on public.bookings;
drop policy if exists "Users can cancel their own bookings" on public.bookings;
drop policy if exists "Users can delete expired own bookings" on public.bookings;
drop policy if exists "Anyone can view booked slots" on public.bookings;
drop policy if exists "Users can view own bookings" on public.bookings;
drop policy if exists "Admins can view all bookings" on public.bookings;

-- Public calendar only needs to know WHICH slots are taken (status='booked').
-- user_id of other users' bookings is still visible to anon via this policy;
-- without access to public.users (locked down above) it is just an opaque UUID.
create policy "Anyone can view booked slots"
  on public.bookings for select
  using (status = 'booked');

-- Users can always see their own bookings (including their cancelled history).
create policy "Users can view own bookings"
  on public.bookings for select
  using (user_id = auth.uid());

-- Admins (role checked via SECURITY DEFINER helper) can see everything.
create policy "Admins can view all bookings"
  on public.bookings for select
  using (public.is_admin());

create policy "Authenticated users can create bookings"
  on public.bookings for insert
  with check (
    status = 'booked'
    and user_id = auth.uid()
    and (booking_date + start_time) >= (now() at time zone 'Asia/Bangkok' + interval '1 hour')
  );

create policy "Users can cancel their own bookings"
  on public.bookings for update
  using (user_id = auth.uid())
  with check (status = 'cancelled' and user_id = auth.uid());

create policy "Users can delete expired own bookings"
  on public.bookings for delete
  using (
    user_id = auth.uid()
    and (booking_date + start_time) <= (now() at time zone 'Asia/Bangkok' - interval '48 hours')
  );

create or replace function public.delete_expired_bookings()
returns void
language sql
security definer
set search_path = public
as $$
  delete from public.bookings
  where (booking_date + start_time) <= (now() at time zone 'Asia/Bangkok' - interval '48 hours');
$$;

revoke all on function public.delete_expired_bookings() from public;

-- Enable pg_cron in Supabase, then schedule this function once:
-- select cron.schedule('delete-expired-pitchhub-bookings', '0 * * * *', $$select public.delete_expired_bookings();$$);
