create table public.bookings (
  id bigint generated by default as identity primary key,
  booking_date date not null,
  pitch smallint not null check (pitch between 1 and 4),
  start_time time not null,
  status text not null default 'booked' check (status in ('booked', 'cancelled')),
  created_at timestamptz not null default now()
);

create unique index bookings_active_slot_idx
  on public.bookings (booking_date, pitch, start_time)
  where status = 'booked';

alter table public.bookings enable row level security;

create policy "Anyone can view active bookings"
  on public.bookings for select
  using (status = 'booked');

create policy "Anyone can create bookings"
  on public.bookings for insert
  with check (status = 'booked');