create table if not exists public.users (
  id uuid primary key default gen_random_uuid(),
  fullname text not null,
  email text not null unique,
  role text not null default 'user' check (role in ('user', 'admin'))
);

create or replace function public.sync_user_id_from_auth()
returns trigger
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if new.id is null then
    new.id := auth.uid();
  end if;

  if new.id is not null and new.id <> auth.uid() then
    new.id := auth.uid();
  end if;

  return new;
end;
$$;

do $$
begin
  if not exists (
    select 1
    from pg_trigger
    where tgname = 'users_sync_id_from_auth'
  ) then
    create trigger users_sync_id_from_auth
    before insert or update on public.users
    for each row
    execute function public.sync_user_id_from_auth();
  end if;
end $$;

-- Backfill existing data: match public.users rows to auth.users by email so bookings.user_id can resolve correctly.
update public.users u
set id = a.id
from auth.users a
where a.email = u.email
  and u.id is distinct from a.id;

alter table public.users enable row level security;

drop policy if exists "Anyone can view users" on public.users;
drop policy if exists "Authenticated users can insert users" on public.users;

create policy "Anyone can view users"
  on public.users for select
  using (true);

create policy "Authenticated users can insert users"
  on public.users for insert
  with check (auth.uid() is not null);

create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id),
  booking_date date not null,
  pitch smallint not null check (pitch between 1 and 4),
  start_time time not null,
  status text not null default 'booked' check (status in ('booked', 'cancelled')),
  created_at timestamptz not null default now()
);

alter table public.bookings
  add column if not exists user_id uuid references auth.users(id);

create unique index if not exists bookings_active_slot_idx
  on public.bookings (booking_date, pitch, start_time)
  where status = 'booked';

alter table public.bookings enable row level security;

drop policy if exists "Anyone can view active bookings" on public.bookings;
drop policy if exists "Anyone can create bookings" on public.bookings;
drop policy if exists "Authenticated users can create bookings" on public.bookings;
drop policy if exists "Users can cancel their own bookings" on public.bookings;
drop policy if exists "Users can delete expired own bookings" on public.bookings;

create policy "Anyone can view active bookings"
  on public.bookings for select
  using (status = 'booked' or user_id = auth.uid());

create policy "Authenticated users can create bookings"
  on public.bookings for insert
  with check (
    status = 'booked'
    and user_id = auth.uid()
    and (booking_date + start_time) >= (now() at time zone 'Asia/Bangkok' + interval '1 hour')
  );

create policy "Users can cancel their own bookings"
  on public.bookings for update
  using (user_id = auth.uid())
  with check (status = 'cancelled' and user_id = auth.uid());

create policy "Users can delete expired own bookings"
  on public.bookings for delete
  using (
    user_id = auth.uid()
    and (booking_date + start_time) <= (now() at time zone 'Asia/Bangkok' - interval '48 hours')
  );

create or replace function public.delete_expired_bookings()
returns void
language sql
security definer
set search_path = public
as $$
  delete from public.bookings
  where (booking_date + start_time) <= (now() at time zone 'Asia/Bangkok' - interval '48 hours');
$$;

revoke all on function public.delete_expired_bookings() from public;

-- Enable pg_cron in Supabase, then schedule this function once:
-- select cron.schedule('delete-expired-pitchhub-bookings', '0 * * * *', $$select public.delete_expired_bookings();$$);